FROM openjdk:11-jre-slim-sid

LABEL maintainer="Bruno Nogueira <ti.brunonogueira at gmail.com"
LABEL version="1.0"

WORKDIR /app

COPY target/app-*.jar /app/review-app.jar

EXPOSE 8080

ENTRYPOINT java	-jar review-app.jar